---

name: Build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      IMAGE_TAG: latest
    steps:
      ##
      ## Setup
      ##

      - name: Checkout
        uses: actions/checkout@v2

      - name: Log in to GitHub Docker Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      ##
      ## Build and push Container image
      ##

      - name: Build and push container image
        uses: docker/build-push-action@v2
        with:
          push: true
          build-args: |
            IMAGE_TAG=${{ env.IMAGE_TAG }}
          tags: |
            ghcr.io/djwhitt/perkeep:${{ env.IMAGE_TAG }}
